#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Configure redirection in Nginx
sudo sed -i 's/location \/ {/location \/redirect_me {/g' /etc/nginx/sites-available/default
sudo sed -i '/location \/redirect_me {/a \\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
